name: BuyPermissionsSystem
version: 1.0.0
author: ProgrammingPanda
main: de.programmingpanda.buypermssystem.MainActivity
commands:
   prl:
      description: Saves and reloads the permissions config
   bp:
      description: Opens the Permissions GUI